proggamera/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name="landing"),

]

proggamera/profilepage/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('teacher/', views.teacherdash, name="teacher_dash"),
    path('student/', views.studentdash, name="student_dash"),
    path('student/classroom', views.s_classroom, name="s_classroom"),
    path('student/classroom/add/<int:pk>',views.add_student_to_classroom, name="student_code"),
    path('student/courses', views.s_courses, name="s_courses"),

    
    path('teacher/classroom/', views.t_classroom, name="t_classroom"),
    path('teacher/excercises/', views.t_excercises, name="t_excercises"),
    path('teacher/excercises/remove/<int:pk>', views.t_remove_excercise, name="t_remove_excercise"),
    path('teacher/excercises/<int:classid>/<int:courseid>', views.t_excercises_course, name="t_excercises_course"),
    path('teacher/excercises/add', views.t_add_excercise, name="t_add_excercise"),
    path('teacher/results',views.t_results, name="t_results"),
    path('teacher/results/<int:classid>/<int:courseid>/overview',views.t_overview, name="result_overview"),
    path('teacher/results/<int:classid>/<int:courseid>/overview/<int:studentid>/studentdetail',views.t_overview_s_detail, name="result_detail"),
    path('teacher/classroom/<int:pk>/<int:course>/', views.curr_classroom, name="curr_classroom"),
    path('teacher/classroom/<int:pk>/add', views.add_students, name="add_students"),
    path('teacher/classroom/<int:classroomid>/add/code', views.add_students_code, name="add_students_code"),
    path('teacher/classroom/<int:pk>/search_students/', views.search_students, name="search_students"),
    path('teacher/classroom/<int:pk>/add/<int:student>', views.added, name="added"),
    path('teacher/classroom/remove/<int:classroom>/<str:student>', views.remove_student , name="remove_student"),
]

proggamera/proggamera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('profilepage/', include('profilepage.urls')),
    path('courses/', include('courses.urls')),

    
]

proggamera/profilepage/models.py
from pyexpat import model
from statistics import mode
from xml.etree.ElementTree import QName
from django.db import models
from courses.models import FillInBlanks, Quiz, VideoWatched, VisitedPage
from user.models import CustomUser
from courses.models import Videos
# Create your models here.

class Course(models.Model):
    course_name=models.CharField(max_length=40)
    def __str__(self):
        return self.course_name
        
class Chapters(models.Model):
    chapter_name=models.CharField(max_length=40)
    chapter_number=models.IntegerField()
    course=models.ForeignKey(Course, on_delete = models.CASCADE)
    def __str__(self):
        return self.chapter_name

class Subchapters(models.Model):
    subchapter_name=models.CharField(max_length=40)
    subchapter_number=models.IntegerField()
    parent_chapter=models.ForeignKey(Chapters, on_delete = models.CASCADE, related_name="sub")
    content=models.TextField(max_length=5000)

    def __str__(self):
        return self.subchapter_name

class Teacher(models.Model):
    user=models.ForeignKey(CustomUser, on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username



class Student(models.Model):
    user=models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    courses=models.ManyToManyField(Course, blank=True)
    license_active=models.BooleanField(null=True ,blank=True)
   
    def __str__(self):
        return self.user.username
    

class Classroom(models.Model):
    name=models.CharField(max_length=30)
    students=models.ManyToManyField(Student)
    courses=models.ManyToManyField(Course)
    teacher=models.ForeignKey(Teacher, on_delete = models.CASCADE)

    def __str__(self):
        return self.name
    

class Excercise(models.Model):
    classroom=models.ForeignKey(Classroom, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    subchapter=models.ForeignKey(Subchapters, on_delete=models.CASCADE)
    deadline=models.DateField()
    teacher=models.ForeignKey(Teacher, on_delete=models.CASCADE)
    excercise_type=models.CharField(max_length=64)
    quiz_excercise=models.ForeignKey(Quiz, on_delete=models.SET_NULL, blank=True, null=True)
    fill_excercise=models.ForeignKey(FillInBlanks, on_delete=models.SET_NULL, blank=True, null=True)
    read_excercise=models.ForeignKey(Subchapters, on_delete=models.SET_NULL, blank=True, null=True, related_name="excercise_subchapter")
    video_excercise=models.ForeignKey(Videos, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.excercise_type}: {self.subchapter} for course: {self.course} " 


class ExcerciseResult(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE)
    excercise=models.ForeignKey(Excercise, on_delete=models.CASCADE)
    turned_in=models.BooleanField()
    turned_in_data=models.DateField(auto_now=True)


class StudentExcercises(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE)
    excercises=models.ManyToManyField(Excercise)


    def __str__(self):
        excercise_list=[]
        for excercise in self.excercises.all():
            excercise_list.append(excercise)
        return f'{self.student} har läxorna {excercise_list}'

proggamera/profilepage/forms.py
from django import forms
from .models import Course
from .models import Student, Classroom, Teacher


class add_class_form(forms.Form):
    courses=Course.objects.all()
    course_list=courses.values_list()
    class_name=forms.CharField(label="Klassens namn ", max_length=50)
    courses = forms.MultipleChoiceField(required = True, label="Kurser " , widget=forms.CheckboxSelectMultiple, choices=course_list)

class add_student_form(forms.Form):
    student=forms.CharField(label="Elevens namn", max_length=100)
    student_email=forms.EmailField(label="Elevens mail", max_length=100)

class add_course_form(forms.Form):
    courses=Course.objects.all()
    course_list=courses.values_list()
    courses = forms.MultipleChoiceField(required = True, label="Kurser " , widget=forms.CheckboxSelectMultiple, choices=course_list)

class DateInput(forms.DateInput):
    input_type = 'date'

class add_excercise_form(forms.Form):
    Excercise_type=[('alla','Alla'),
     ('quiz','Quiz'),
     ('läs kapitlet','Läs kapitlet'),
     ('se video', 'Se video'),
     ('fill in blanks', 'Fill in blanks')]
    excercises=forms.MultipleChoiceField(
        required=False,
        label="Välj uppgifter",
        widget=forms.CheckboxSelectMultiple,
        choices=Excercise_type,
    )
    deadline = forms.DateField(widget=DateInput, label="Deadline")
   
   

        

proggamera/profilepage/views.py
from email import message
from http.client import HTTPResponse
from msilib.schema import Class
from multiprocessing import context
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from courses.models import Quiz, VisitedPage
from courses.models import FillInBlanks, Videos
from .forms import *
from .models import Course, Chapters, StudentExcercises, Subchapters, Student, Teacher, Classroom, Excercise, ExcerciseResult
from user.models import *
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.contrib import messages
# Create your views here.


def teacherdash(request):
    curr_teacher = Teacher.objects.get(user=request.user)
    teachers_classrooms = Classroom.objects.filter(teacher=curr_teacher)
    teachers_courses = Course.objects.filter(classroom__teacher=curr_teacher)
    courses = []
    for course in teachers_courses:
        if course not in courses:
            courses.append(course)
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'teacherdash.html', {'classrooms': teachers_classrooms, 'courses': courses})


def studentdash(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            user = CustomUser.objects.get(username=request.user.username)
            user.is_student = True
            user.save()
            return render(request, 'studentdash.html')
        else:
            request.user.is_student = True
            return render(request, 'studentdash.html')
    return render(request, 'studentdash.html')


def t_classroom(request):
    try:
        curr_user = Teacher.objects.get(user=request.user)
        classes = Classroom.objects.filter(teacher=curr_user)

    except Classroom.DoesNotExist:
        classes = []
    if request.method == 'POST':
        form = add_class_form(request.POST)
        if form.is_valid():
            class_name = form.cleaned_data["class_name"]
            chosen_courses = form.cleaned_data["courses"]
            if request.user.is_teacher:
                user = CustomUser.objects.get(username=request.user.username)
                try:
                    temp_teach = Teacher.objects.get(user=request.user)
                except Teacher.DoesNotExist:
                    add_teacher = Teacher(user=request.user)
                    add_teacher.save()
                    temp_teach = Teacher.objects.get(user=request.user)

                new_classroom = Classroom(name=class_name, teacher=temp_teach)
                new_classroom.save()
                if len(chosen_courses) > 1:
                    for i in range(len(chosen_courses)):
                        new_classroom.courses.add(chosen_courses[i])
                else:
                    new_classroom.courses.add(chosen_courses[0])
                new_classroom.save()
                classes = Classroom.objects.filter(name=class_name)
                return redirect('t_classroom')
            else:
                return render(request, 'landing.html')
    else:
        form = add_class_form()

    return render(request, 'teacher_classroom.html', {"form": form, "classes": classes})


def s_classroom(request):
    try:
        curr_user = Student.objects.get(user=request.user)
        classes = Classroom.objects.filter(students=curr_user)
    except Classroom.DoesNotExist:
        classes = []

    return render(request, 'student_classrooms.html', {"classes": classes})


def s_courses(request):
    curr_user = Student.objects.get(user=request.user)
    courses = Course.objects.filter(student=curr_user)
    print(courses)

    return render(request, 'student_courses.html', {"courses": courses})


def curr_classroom(request, pk, course):
    class_path = "127.0.0.1:8000/profilepage/student/classroom/" + \
        str(pk)+"/"+str(course)
    classroom = Classroom.objects.get(id=pk)
    course = Course.objects.get(id=course)
    students = Student.objects.filter(classroom__id=pk)
    if request.method == "POST":
        form = add_course_form(request.POST)
        if form.is_valid():
            chosen_courses = form.cleaned_data["courses"]
            if len(chosen_courses) > 1:
                    for i in range(len(chosen_courses)):
                        classroom.courses.add(chosen_courses[i])
            else:
                classroom.courses.add(chosen_courses[0])
    else:
        form = add_course_form()
    context = {'classroom': classroom, 'course': course,
        'students': students, 'form': form, "code": class_path}
    return render(request, 'classroom.html', context)


def add_students(request, pk):
    curr_classroom = Classroom.objects.get(id=pk)
    # print(curr_classroom)
    if request.method == 'POST':
        form = add_student_form(request.POST)

        if form.is_valid():
            student = form.cleaned_data["student_name"]

    else:
        form = add_student_form()
        student = ""

    return render(request, 'add_student.html', {"added_students": student, "form": form, "classroom": curr_classroom})


def add_students_code(request, classroomid):
    class_path = "127.0.0.1:8000/profilepage/student/classroom/add/" + \
        str(classroomid)
    courses = Course.objects.filter(classroom__id=classroomid)
    students = Student.objects.filter(classroom__id=classroomid)
    curr_classroom = Classroom.objects.get(id=classroomid)
    context = {'classroom': curr_classroom, 'courses': courses,
        'students': students, 'code': class_path}
    return render(request, 'classroom.html', context)


def add_student_to_classroom(request, pk):
    try:
        curr_student = Student.objects.get(user=request.user)
        classroom = Classroom.objects.get(id=pk)
        try:
            classroom.students.get(user=request.user)
            messages.info(request, 'Du är redan i klassrummet',
                          extra_tags="added_classroom")
            classes = Classroom.objects.filter(students=curr_student)
        except curr_student.DoesNotExist:
            print("hello?")
            classroom.students.add(curr_student)
            classroom.save()
            try:
                classes = Classroom.objects.filter(students=curr_student)
                messages.info(request, 'Du blev tillagd i klassrummet',
                              extra_tags="added_classroom")
            except Classroom.DoesNotExist:
                classes = []
                messages.info(request, 'Klassrummet fanns inte',
                              extra_tags="added_classroom")

    except Classroom.DoesNotExist:
        messages.info(request, 'Klassrummet fanns inte',
                      extra_tags="added_classroom")
        try:
            classes = Classroom.objects.filter(students=curr_student)
        except Classroom.DoesNotExist:
            classes = []

    return render(request, 'student_classrooms.html', {'classes': classes})


def remove_student(request, classroom, student):
    curr_student = Student.objects.get(id=student)
    curr_classroom = Classroom.objects.get(id=classroom)
    curr_classroom.students.remove(curr_student)
    students = Student.objects.filter(classroom__id=classroom)
    context = {'classroom': curr_classroom, 'students': students}
    return HttpResponse("")


def add_class(request):
    return render(request, 'teacher_classroom.html')


def invite_students(request):
    # change from django-invitations to own model
    # Invitation = get_invitation_model()
    # Invitation.objects.all().delete()
    # todo: Check if user already has been invited for this classroom
    # invite = Invitation.create('philip.gullberg
    # @ntig.se', inviter=request.user)
    # invite.save()
    # invite.send_invitation(request)
    return


def search_students(request, pk):
    curr_classroom = Classroom.objects.get(id=pk)
    if request.method == "POST":
        search_text = request.POST.get("search")
        result = Student.objects.filter(user__username__contains=search_text)
    else:
        result = ""
    return render(request, 'search_result.html', {'students': result, "classroom": curr_classroom})


def added(request, pk, student):
    curr_classroom = Classroom.objects.get(id=pk)
    curr_student = Student.objects.get(id=student)
    curr_classroom.students.add(curr_student)
    class_courses = Course.objects.filter(classroom__name=curr_classroom)
    for course in class_courses:
        curr_student.courses.add(course)
    message = f"Lade till {curr_student}"
    return HttpResponse("Added")


def t_results(request):
    curr_teacher = Teacher.objects.get(user=request.user)
    teachers_classrooms = Classroom.objects.filter(teacher=curr_teacher)
    classroom_courses = Course.objects.filter(classroom__teacher=curr_teacher)
    teachers_students = Student.objects.filter(classroom__teacher=curr_teacher)

    return render(request, 'teacher_results.html', {'students': teachers_students, 'classrooms': teachers_classrooms, 'courses': classroom_courses})


def t_overview(request, classid, courseid):
    curr_teacher = Teacher.objects.get(user=request.user)
    curr_classroom = Classroom.objects.get(id=classid)
    curr_course = Course.objects.get(id=courseid)
    course_chapters = Chapters.objects.filter(course=curr_course)
    course_students = Student.objects.filter(
    courses=curr_course, classroom=curr_classroom)
    visitedpages = VisitedPage.objects.all()
    videos=Videos.objects.all()
    return render(request, 't_result_overview.html', {"videos":videos,"teacher": curr_teacher, "course": curr_course, "classroom": curr_classroom, "chapters": course_chapters, "students": course_students, "visited": visitedpages})


def t_overview_s_detail(request, classid, courseid, studentid):
    curr_student = Student.objects.get(id=studentid)
    curr_class = Classroom.objects.get(id=classid)
    curr_course = Course.objects.get(id=courseid)

proggamera/profilepage/templates/add_student.html
{% extends 'profile_layout.html' %}
{% block content%}
<div class="stnd-btn" type="button"><a href="{% url 'curr_classroom' classroom.id %}" style="text-decoration: none; color:white;">
    <i class="fas fa-arrow-left"></i> Gå tillbaks</a></div>
<h1>Klassrum: {{classroom}}</h1>
<h3>Sök på dina elever och lägg till de till ditt klassrum</h3>

<!-- <form class="">
    {%csrf_token%}
    <fieldset>
        <label for="search">Sök elev:</label>
        <input type="text" hx-post="{% url 'search_students' classroom.id %}" name='search'
            hx-target='#student_results' hx-trigger="keyup changed delay 500ms"
            class="form-control-sm mr-2">
    </fieldset>

</form>
<div id="student_results" class="mr-auto" >
    {% if searched_students %}
    
    <ul>
        <h5>Elever:</h5>
        
        {% for student in searched_students %}
        
            <li>
                {{student}}
                <form  style="display:inline-block">
                   <button hx-post="{% url 'add_students' student %}"
                    hx-target="#added_students" >Lägg till</button> 
                    
                </form>
                
            </li>
            
        
        {%endfor%}
        
    </ul>
    {% else %}
        {% if added %}
            {{added}}
        {% else %}
        <p></p>
        {%endif%}
    {%endif%}
</div> -->
{{message}}
<div id="add_student_form" >
    <form action="{% url 'search_students' classroom.id %}" method="POST">
        {% csrf_token %}
        <label for="search">Sök elev...</label>
        <input type="search" name="search" id="search_student">
        <input type="submit" value="Sök">
        <br>
        <br>
       <!--  {{ form }} -->
       
    </form>
</div>

{%endblock%}

proggamera/profilepage/templates/search_result.html
{% block content%}
<div id="student_results" class="mr-auto" >
    {%for student in students %}
    <div class="d-flex-column">
        <div class="d-flex align-items-center justify-content-between row{{forloop.counter}}">
            <div>{{student}} </div>
            <div class="btn btn-success ms-5" type="button">
                <a type="submit" hx-swap="innerHTML" hx-target =".row{{forloop.counter}}" hx-post="{% url 'added' classroom.id student.id %}" style="text-decoration: none; color:white;">+ Lägg till</a></div>
        </div>
        <hr>
    </div>
    {%endfor%}
</div>
{%endblock%}

proggamera/profilepage/templates/student_courses.html
{% extends 'profile_layout.html' %}

{% block content%}
<h3>Här är dina kurser</h3>
<hr>
{% for course in courses%}
    <div class="d-flex align-items-center pb-4">
        <h4 class="py-2  px-3">{{course}}</h4>
        <div>
            <a href="{% url 'subchapter' course.id 1 1 %}?page=1" style="text-decoration: none; color:white;">
                <div class="stnd-btn " type="button">Gå till kurs  <i class="fas fa-arrow-right"></i></div>
            </a>
            
        </div>
        
    </div>
{%endfor%}
{%endblock%}

proggamera/profilepage/templates/t_excercises_course.html
{% extends 'profile_layout.html' %}

{% block content%}

{% load static %}
<div class="d-flex justify-content-between align-items-center mt-4">
    <div class="col-sm-8">
        <div class="d-flex align-items-center justify-content-between">
            <h3 class="mt-3">Uppgifter: {{classroom.name}} - {{course}}</h3>
            <i class="fa-solid fa-gear fa-xl pt-3"></i>
        </div>
        <hr>
    </div>
    <div class="col-sm-4 text-center">
        <button class="go-button position-relative">
            <a class="no-link stretched-link" href="{% url 'courses' course.id%}/?page=1 ">Gå till kursen <i class="fas fa-arrow-right ps-3"></i> </a>
        </button>
    </div>
</div>

<div class="d-flex gap-5 flex-wrap pb-3">
    <div class="active_excercise_card d-flex-column mt-4 mb-1 p-4 flex-basis-auto position-relative">
        <div class="d-flex justify-content-between align-items-center">
            <div class="col-sm-8">
                <h4><b>Aktiva uppgifter</b></h4>

            </div>
            <div class="dropdown">

                <div class="icon_drop" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class=" fa-solid fa-ellipsis-vertical fa-xl me-0"></i>
                </div>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" data-toggle="modal" data-target="#editexcercise" href="">Redigera
                        uppgifter</a>
                </div>
            </div>
            <div class="modal fade" id="editexcercise" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Redigera uppgifter</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Här kan du ta bort uppgifter eller ändra datum</p>
                            <div>
                                <div class="d-flex-column">

                                    <table class="col-sm-12">
                                        <tr>
                                            <th>Uppgift</th>
                                            <th>Deadline</th>
                                            <th>Ta bort</th>
                                        </tr>

                                        {% for excercise in classroom.excercise_set.all %}
                                            {% if excercise.course == course%}
                                           

                                        <tr id="row{{forloop.counter}}">
                                            <div class="d-flex justify-content-between pb-2">
                                                <div>
                                                    <td>{{excercise.excercise_type}} - {{excercise.subchapter}}
                                                   {{excercise.subchapter.parent_chapter.chapter_number}}.{{excercise.subchapter.subchapter_number}}
                                                </td>
                                                </div>
                                                <div>
                                                   <td>Inlämning: {{excercise.deadline.day}}/{{excercise.deadline.month}}</td> 
                                                </div>
                                            </div>
                                               <td><button class="btn btn-danger" type="submit" hx-swap="innerHTML"
                                                    hx-target="#row{{forloop.counter}}"
                                                    hx-post="{% url 't_remove_excercise' excercise.id %}">X</button></td> 
                                                
                                        </tr>

                                        {%endif%}
                                        {%endfor%}
                                        </div>
                                </div>
                            </div>
                            </table>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

</div>
<hr>
<table class="w-100">
    <tr >
        <th>Typ</th>
        <th>Kapitel</th>
        <th>Deadline</th>
        <th>Resultat</th>
    </tr>
    {% for excercise in classroom.excercise_set.all %}
        {% if excercise.course == course%}
        <tr >
                <td>
                    {{excercise.excercise_type}}</td> 
                    <td>{{excercise.subchapter.parent_chapter.chapter_number}}.{{excercise.subchapter.subchapter_number}}
                        {{excercise.subchapter}}</td>
                    <td class="text-center">
                    {{excercise.deadline.day}}/{{excercise.deadline.month}}
                </td>
                <td class="text-center"><a class="link-icon" href="{% url 'result_overview' classroom.id course.id%}"><i class="fas fa-regular fa-chart-simple"></i></a></td>
                </div>
        </tr>
        {%endif%}
    
    {%endfor%}
</table>


</div>
<div class="give_excercise_card  d-flex-column mt-4 mb-1 p-4 flex-basis-auto position-relative">
    <div class="d-flex justify-content-between align-items-center">
        <div class="col-sm-8 ">
            <h4><b>Ge uppgifter för {{course}}</b></h4>
        </div>
        <div class="col-sm-1">
            <i class="fas fa-regular fa-info-circle"></i>
        </div>
    </div>
    <hr>
    <div class="d-flex-column">
        <div>
            <div id="accordion">
                {% for chapter in course.chapters_set.all%}

                <div class="card">

                    <div class="card-header d-flex justify-content-between align-items-center" data-toggle="collapse"
                        data-target="#collapse{{forloop.counter}}" id="headingOne">
                        <h6 class="mb-0">

                            <button class="btn" data-toggle="collapse" data-target="#collapse{{forloop.counter}}"
                                aria-expanded="false" aria-controls="collapse{{forloop.counter}}">
                                <h7>{{forloop.counter0}}. {{chapter}} </h7>
                            </button>
                        </h6>
                        <i class="fas fa-arrow-down ms-5"></i>
                    </div>


                    <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="headingOne"
                        data-parent="#accordion">
                        <div class="card-body">

                            {% for subchap in chapter.sub.all %}

                            <div class="sub-text d-flex justify-content-between align-items-center">
                                <a class="ps-4 text-decoration-none"
                                    href="{% url 'subchapter' course.id chapter.chapter_number 1 %}?page={{forloop.counter}}">{{forloop.counter0}}.
                                    {{subchap}}</a>
                                <button data-toggle="modal" data-target="#addexcercisemodal" data-whatever="{{subchap}}"
                                    href="" class="homework_button d-flex align-items-center">
                                    <p class="m-0 me-1">Ge läxa</p>
                                    <img width="25px" class="align-self-end"
                                        src="{% static 'profilepage/ic_homework.png' %}" alt="">
                                </button>
                            </div>
                            <hr>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>


            {%endfor%}

        </div>
    </div>


</div>
<!-- Add excercise modal -->
<div class="modal fade" id="addexcercisemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Lägg till uppgift för {{error}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="d-flex flex-wrap gap-2 pb-5">
                        {% for field in form.excercises %}
                        <div class="excercise_form" id="box{{forloopcounter}}">
                            {{field}}

                        </div>
                        {%endfor%}
                        <input class="excercise_subchap" name="subchapter" type="hidden" value="hej"></input>
                    </div>
                    {{form.deadline}}
                    <br>
                    <input type="submit" value="Spara">
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('.excercise_form').on('click', function () {
            let box = $(this)
            var checkbox = box[0].childNodes[1].childNodes[0];
            console.log(checkbox)
            if (checkbox.checked == false) {
                checkbox.checked = true;
            } else {
                checkbox.checked = false;
            }
        });
        $('#addexcercisemodal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var recipient = button.data('whatever')
            var modal = $(this)
            modal.find('.modal-title').text('Lägg till uppgift för ' + recipient)
            var subinput = modal.find('.excercise_subchap')[0].value = recipient;
        })
    </script>
    {%endblock%}

proggamera/profilepage/templates/temp_added.html
<div id="added_students">
                                
    {% if added_students%}
    <ul>
        <form  style="display:inline-block">
            <button href="" >Lägg till alla</button> 
             
         </form>
        {% for student in added_students %}
        <li>{{student}}</li>
        {% endfor %}
        
        
    </ul>
    {% else %}
    <p>Inga tillagda</p>
    {%endif%}
</div>