proggamera/courses/urls.py
from django.urls import path,re_path
from . import views

urlpatterns = [
    path('course/<str:courseid>/chapter/1/subchapter/1', views.course, name="courses"),
    path('course/<str:courseid>/chapter/<str:chapterid>/subchapter/<str:pageid>/', views.subchapter, name="subchapter"),
    path('course/<str:videoid>', views.timer, name="timer"), 


]

proggamera/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name="landing"),

]

proggamera/proggamera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('profilepage/', include('profilepage.urls')),
    path('courses/', include('courses.urls')),

    
]

proggamera/courses/models.py
from django.db import models
from embed_video.fields  import  EmbedVideoField
from .fields import NonStrippingTextField

# Create your models here.

class Videos (models.Model):
    video_title=models.CharField(max_length=50)
    video_descp = models.CharField(max_length=200)
    video = EmbedVideoField()
    parent=models.ForeignKey("profilepage.Subchapters", on_delete=models.SET_NULL, null=True)

    def  __str__(self):
	    return  self.video_title

class Quiz(models.Model):
    parent=models.ForeignKey("profilepage.Subchapters", on_delete=models.SET_NULL, null=True)
    question = models.CharField(max_length=200,null=True)
    op1 = models.CharField(max_length=200,null=True)
    op2 = models.CharField(max_length=200,null=True)
    op3 = models.CharField(max_length=200,null=True)
    op4 = models.CharField(max_length=200,null=True)
    ans = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.question

class Quizresult(models.Model):
    quiz=models.ForeignKey(Quiz, on_delete=models.SET_NULL, null=True)
    students=models.ForeignKey("profilepage.Student", on_delete=models.SET_NULL, null=True)
    answers=models.CharField(max_length=100)
    result=models.IntegerField()

    def __str__(self):
        return f"{self.students} result for {self.quiz}"

class FillInBlanks(models.Model):
    subchapter=models.ForeignKey("profilepage.Subchapters", on_delete=models.SET_NULL, null=True)
    title=models.CharField(max_length=60)
    description=models.CharField(max_length=200, null=True,blank=True)
    code_before = NonStrippingTextField(max_length=500,blank=True,)
    code_on_input_line_before=NonStrippingTextField(max_length=50,blank=True)
    code_on_input_line_after=NonStrippingTextField(max_length=50,blank=True)
    input_length=models.CharField(max_length=50, blank=True)
    code_after = NonStrippingTextField(max_length=500, blank=True)
    answer=models.CharField(max_length=100, blank=True)
    hint=models.CharField(max_length=500)
    
    def __str__(self):
        return f"{self.title}: {self.description}"

class FillInBlanksResults(models.Model):
    parent=models.ForeignKey(FillInBlanks, on_delete=models.SET_NULL, null=True)
    student=models.ForeignKey("profilepage.Student", on_delete=models.CASCADE)
    answer=models.CharField(max_length=50)
    result=models.IntegerField()

    def __str__(self):
        return f"{self.parent}: {self.student}: result {self.result}"
        
class VisitedPage(models.Model):
    page=models.URLField()
    student=models.ForeignKey("profilepage.Student", on_delete=models.CASCADE)
    subchapter=models.ForeignKey("profilepage.Subchapters", on_delete=models.SET_NULL, null=True)
    visited=models.BooleanField()

    
    def __str__(self):
        return f"{self.student} visited {self.subchapter}: {self.visited}"

class VideoWatched(models.Model):
    parent=models.ForeignKey("profilepage.Subchapters", on_delete=models.CASCADE)
    video=models.ForeignKey(Videos, on_delete=models.CASCADE)
    student=models.ForeignKey("profilepage.Student", on_delete=models.CASCADE)
    watchtime=models.IntegerField()
    watched=models.BooleanField()

    def __str__(self):
        return f"{self.student} watched {self.video}: {self.watched}"

proggamera/courses/views.py
from queue import Empty
from django.shortcuts import redirect, render
from profilepage.models import *
from django.core.paginator import Paginator
from .models import *
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def course(request,courseid):
    curr_course=Course.objects.get(id=courseid)
    chapters=Chapters.objects.filter(course=curr_course)
    
    #subchapters=Subchapters.objects.filter(parent_chapter=chapters)
    return render(request,"course.html", {"course":curr_course,"chapters":chapters})

""" def subchapter(request,courseid, subchapterid):
    
    curr_course=Course.objects.get(id=courseid)
    chapters=Chapters.objects.filter(course=curr_course)
    subchapter=Subchapters.objects.get(id=subchapterid)
    return render(request,"course.html", {"course":curr_course,"chapters":chapters, "subchapter": subchapter})
 """

def subchapter(request,courseid,chapterid, pageid):
    curr_student=Student.objects.get(user=request.user)
    
    curr_course=Course.objects.get(id=courseid)
    chapters=Chapters.objects.filter(course=curr_course)
    curr_chapter=Chapters.objects.get(chapter_number=chapterid, course__id=courseid)
    subchapters=Subchapters.objects.filter(parent_chapter=curr_chapter)
    
    p=Paginator(subchapters,1)
    
    pageid = request.GET.get('page')
    page_obj=p.get_page(pageid)
    if(pageid):
        curr_subchapter=Subchapters.objects.get(parent_chapter=curr_chapter,subchapter_number=(int(pageid)-1))
    else:
        curr_subchapter=Subchapters.objects.get(parent_chapter=curr_chapter,subchapter_number=(0))

    if not VisitedPage.objects.filter(student=curr_student, subchapter=curr_subchapter).exists():
        VisitedPage(student=curr_student,page=request.build_absolute_uri(), visited=True, subchapter=curr_subchapter).save()
    try:              
        video=Videos.objects.get(parent=curr_subchapter)
    except Videos.DoesNotExist:
        video="none"
    curr_fillblanks= FillInBlanks.objects.filter(subchapter=curr_subchapter)
    try:
        student_fill_result=FillInBlanksResults.objects.filter(parent=curr_fillblanks[0],student=curr_student)
    except IndexError:
        student_fill_result=[]

    curr_quiz=Quiz.objects.filter(parent=curr_subchapter)
    if request.method == 'POST':
        answer_dic=list(request.POST.items())

        #code for fill_in_blanks post:
        for i in range (0,len(answer_dic)):
            if(answer_dic[i][0]=="user_input"):
                curr_student_fill_result=FillInBlanksResults.objects.filter(parent=curr_fillblanks[0],student=curr_student)
                if answer_dic[i][1]==curr_fillblanks[0].answer:
                    if not curr_student_fill_result:
                        curr_student_fill_result=FillInBlanksResults(parent=curr_fillblanks[0],student=curr_student,answer=answer_dic[i][1],result=1 )
                        curr_student_fill_result.save()
                    else:
                        if answer_dic[i][1] != curr_student_fill_result[0].answer:
                            curr_student_fill_result.update(answer=answer_dic[i][1], result=1)
                    
                    return render(request, "fill_in_results.html",{'fill_in_blanks':curr_fillblanks,"student_fill_result":curr_student_fill_result})
                else:
                    if not curr_student_fill_result:
                        curr_student_fill_result=FillInBlanksResults(parent=curr_fillblanks[0],student=curr_student,answer=answer_dic[i][1],result=0 )
                        curr_student_fill_result.save()
                    else:
                        curr_student_fill_result=FillInBlanksResults.objects.filter(parent=curr_fillblanks[0],student=curr_student)
                        if answer_dic[i][1] != curr_student_fill_result[0].answer:
                            curr_student_fill_result.update(answer=answer_dic[i][1], result=0)
                    

                    return render(request, "fill_in_results.html",{'fill_in_blanks':curr_fillblanks,"student_fill_result":curr_student_fill_result})
        student_answers=[]
        student_score=[]
        #Goes through all questions and checks if students anwer is same as the right answer
        score=0
        for i in range (0,len(answer_dic)):
            if answer_dic[i][1] == answer_dic[i][0]:    
                score+=1
                student_score.append("1")
            else:
                student_score.append("0")
            student_answers.append(answer_dic[i][1])
            
        #goes through all questions and saves the result of the quiz for the curr student
        student_answers.remove(answer_dic[0][1])
        #pop the first element because it only has csrf_key inside
        del student_score[0]
        count=0
        for q in curr_quiz:
            if not (Quizresult.objects.filter(quiz=q,students=curr_student)):
                student_result=Quizresult(quiz=q, students=curr_student, answers=student_answers[count], result=student_score[count])
                student_result.save()
                count+=1
        #implement so student can save result for specific quiz
        num_questions=len(answer_dic)-1

        
        return render(request,"course.html", {"course":curr_course,"chapters":chapters, "page_obj": page_obj,'score':score, 'num_questions':num_questions,'fill_in_blanks':curr_fillblanks,"student_fill_result":student_fill_result,'video':video})
    try:
        data=Quizresult.objects.filter(quiz=curr_quiz[0],students=curr_student)
        if data.exists():
            return render(request,"course.html", {"course":curr_course,"chapters":chapters, "page_obj": page_obj,'score':data[0].result, 'num_questions':len(curr_quiz),'fill_in_blanks':curr_fillblanks,"student_fill_result":student_fill_result,'video':video})
        else:
            return render(request,"course.html", {"course":curr_course,"chapters":chapters, "page_obj": page_obj,'fill_in_blanks':curr_fillblanks,"student_fill_result":student_fill_result,'video':video})
    except IndexError:
        return render(request,"course.html", {"course":curr_course,"chapters":chapters, "page_obj": page_obj,'fill_in_blanks':curr_fillblanks,"student_fill_result":student_fill_result,'video':video})

def timer(request, videoid):
    data=list(request.POST.items())
    curr_student=Student.objects.get(user=request.user)
    curr_video=Videos.objects.get(id=videoid)
    student_watchtime=int(data[0][1])
    url=data[0][0]
    try: 
        videowatch=VideoWatched.objects.get(video=curr_video, student=curr_student)
        videowatch.watched=True
        videowatch.watchtime+=student_watchtime
        videowatch.save()

    except ObjectDoesNotExist:
        new_watchtime=VideoWatched(student=curr_student, video=curr_video, watched=True, watchtime=student_watchtime)
        new_watchtime.save()
    return redirect(url)

proggamera/courses/templates/course.html
{% extends 'profile_layout.html' %}

{% block extrahead%}
{% load static %}
<link rel="stylesheet" href="{% static 'courses/style.css' %}">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/monokai.min.css">
<script type="text/javascript" src="https://www.youtube.com/iframe_api"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js">
</script>
<script src="{% static 'courses/script.js' %}"></script>

<script>
    hljs.highlightAll();
</script>
<script>
    hljs.initLineNumbersOnLoad();
</script>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>


{%endblock%}
{% block sidebar %}

<section id="sidebar" class="sidebar-course close">
    <div>
        <div id="accordion">

            <h4 id="sidebarCollapse" style="cursor:pointer;"
                class="text-center pb-2 d-flex justify-content-around align-items-center">{{course}} <i
                    id="sidebarCollapse" class="fas fa-solid fa-bars fa-sm"> </i></h4>
            {% for chapter in chapters%}

            <div class="card">

                <div class="card-header d-flex justify-content-between align-items-center" data-toggle="collapse"
                    data-target="#collapse{{forloop.counter}}" id="headingOne">
                    <h6 class="mb-0">

                        <button class="btn btn-link  " data-toggle="collapse" data-target="#collapse{{forloop.counter}}"
                            aria-expanded="false" aria-controls="collapse{{forloop.counter}}">
                            <h7>{{forloop.counter0}}. {{chapter}} </h7>
                        </button>
                    </h6>
                    <i class="fas fa-arrow-down ms-5"></i>
                </div>


                <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="headingOne"
                    data-parent="#accordion">
                    <div class="card-body">

                        {% for subchap in chapter.sub.all %}

                        <div class="sub-text">
                            <p class="ps-4"><a class=""
                                    href="{% url 'subchapter' course.id chapter.chapter_number 1 %}?page={{forloop.counter}}">{{forloop.counter0}}.
                                    {{subchap}}</a></p>
                        </div>
                        {%endfor%}
                    </div>
                </div>
            </div>
        </div>


        {%endfor%}

    </div>
</section>
{%endblock%}
{% block content %}
<div class="congrats">
    <lottie-player class="player" src="https://assets3.lottiefiles.com/packages/lf20_lg6lh7fp.json"
        background="transparent" speed="1" style="width: 80%; height: 80%;"></lottie-player>
</div>
<div id="cont" class="d-flex justify-content-center course-content pt-2 mb-5 pb-4">
    {% if page_obj %}
    {% load embed_video_tags %}
    {% for subchapter in page_obj%}

    <div class="cont ms-5 w-75 pl-5 pr-3">
        <!-- <pre><div class="editor"></div></pre>
            <input id="run-button" type="submit" value="Kör"> -->

    <div class="course-content pt-3 ">
        <h3><b>{{subchapter.subchapter_number}}. {{subchapter}}</b></h3>
    </div>
    {% if video %}
        {% if video.parent == subchapter %}
                <div id="player">
                    {% video video.video 'tiny' %}
                
                </div>
                <form class="timerform" hx-post="{% url 'timer' video.id %}" hx-swap="none">
                    <input  id="timer" type="hidden" value="0" name="{{request.build_absolute_uri}}">
                    <input id="timerformsubmit" type="submit" style="display:none">
                </form>
        {%endif%}
                    
    {%endif%}
        <div class=" pb-4 ">
            <p class="text-justify">{% autoescape off %}{{subchapter.content}}{% endautoescape %}</p>
        </div>
        <br>
        {% if fill_in_blanks %}
        {% for fill_in_blank in fill_in_blanks%}

        <div class="fill-in-the-blank p-3 mb-3 rounded ">
            <h3>Fyll i resterande kod: {{fill_in_blank.title}}</h3>
            <p>{{fill_in_blank.description}}</p>
            <div class="fill-in-part p-3 rounded">
                <div class="input">


                    <div class="code-text">{{fill_in_blank.code_before}}
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="code-text">{{fill_in_blank.code_on_input_line_before}}</div>


                        <form class="d-flex align-items-center" hx-post="" hx-swap="innerHTML" hx-target="#result">
                            {%csrf_token%}

                            <input class="input-field" id="fill-in-1" type="text" name="user_input"
                                size="{{fill_in_blank.input_length}}" {%  if student_fill_result.first.answer %}
                                value="{{student_fill_result.first.answer}}" {%else %} placeholder="Svar" {%endif%}>

                            <input class="input-field" id="answer" type="hidden" value="{{fill_in_blank.answer}}">
                            
                            <div class="code-text">{{fill_in_blank.code_on_input_line_after}}</div>

                            
                    </div>
                    <div class="code-text ">{{fill_in_blank.code_after}}</div>
                    

                    <div class="pt-3 pr-2 mt-5 d-flex justify-content-between">
                        <div>
                        <input class="fill-in-answer px-2" type="submit" value="Svara">
                        <input class="fill-in-hint px-2 " type="button" value="Hint">
                        <input class="fill-in-facit px-2" type="button" value="Facit">
                        </div>
                        <div id="result" class="ms-2">
                            {%if student_fill_result.first.result == 1 %}
                            <i class="fa-solid fa-circle-check fa-2xl align-self-end"></i>
                            {%else%}
                            <i class="fa-solid fa-circle-xmark fa-2xl align-self-end"></i>
                            {%endif%}
                        </div>
                    </div>
                    </form>
                </div>

                <div class="hint-text ">
                    <h6>Hint:</h6>
                    <p>{{fill_in_blank.hint}}</p>
                </div>
                <div class="facit-text ">
                    <h6>Svar:</h6>
                    <p>{{fill_in_blank.answer}}</p>
                </div>
            </div>
            </div>
            {%endfor%}
            {%endif%}
            {% if subchapter.quiz_set.all %}
            {% if score >= 0 %}
            <div class="quiz pb-3 p-2 pl-5 pt-4">
                <h3>Quiz</h3>
                <p>Resultat: {{score}} av {{num_questions}}</p>
            </div>

            {%else%}
            <div class="quiz  p-2 pl-5 pt-4">
                <h3>Quiz</h3>
                {% for quiz in subchapter.quiz_set.all %}
                <form method="POST" action="" class="pt-1 pb-2 ">
                    {% csrf_token %}
                    <label for="{{quiz.question}}"></label>
                    <h6>{{quiz.question}}</h6></input>
                    <input type="radio" name="{{quiz.question}}" value="{{quiz.question}}" hidden></input>
                    <input type="radio" name="{{quiz.op1}}" id="op1" value="{{quiz.op1}}"> {{quiz.op1}}</input>
                    <br>
                    <input type="radio" name="{{quiz.op1}}" id="op2" value="{{quiz.op2}}"> {{quiz.op2}}</input>
                    <br>
                    <input type="radio" name="{{quiz.op1}}" id="op3" value="{{quiz.op3}}"> {{quiz.op3}}</input>
                    <br>
                    <input type="radio" name="{{quiz.op1}}" id="op4" value="{{quiz.op4}}"> {{quiz.op4}}</input>

                    <br>
                    <br>
                    {%endfor%}
                    <input type="submit" value="Skicka in svar">
                </form>
            </div>

            {%endif%}
            {%endif%}
            {%endfor%}
            {%endif%}

        </div>
        <footer class="footer fixed-bottom d-flex justify-content-between align-items-center">

            <div id="sidebarOpen" class="">
                <h5 class="ms-5 ">{{course}}<i class="fas fa-solid fa-bars fa-sm ms-5"></i></h5>
            </div>
            <div class="d-flex  justify-content-around align-items-center">
                {% if page_obj.has_previous %}
                <div class="back-button"> <i class=" fas fa-solid fa-angle-left"></i> <a style="color:black;"
                        href="?page={{ page_obj.previous_page_number }}"> Bakåt</a></div>
                {% endif %}
                <p class="ms-2 me-2 pt-3">Sida {{ page_obj.number }} av {{ page_obj.paginator.num_pages }}</p>
                {% if page_obj.has_next %}
                <div class="next-button"><a style="color:white;" href="?page={{ page_obj.next_page_number }}"> Nästa
                    </a> <i class=" fas fa-solid fa-angle-right"></i></div>
                {%else%}
                <!-- TODO 
        Lägg till så att man hoppar till nästa kapitel, eller att man får bekräftelse att man är klar på något sätt
        -->
                <div class="btn-success p-1"><a style="color:white;"> Klar med kapitlet </a> <i
                        class=" fas fa-solid fa-angle-right"></i></div>
                {% endif %}

            </div>
            <div>
                <div id="sidebar" class="ms-5 me-5">
                    <h5>Uppgifter<i class="fas fa-solid fa-bars fa-sm ms-3 me-2"></i></h5>
                </div>
            </div>
        </footer>
        <!-- <script type="module">
    import {CodeJar} from 'https://medv.io/codejar/codejar.js'
    let jar = CodeJar(document.querySelector('.editor'),highlight);
    let code = jar.toString();

    function highlight(){
        let editor = document.querySelector('.editor');
        editor.classList.add('language-python');
        hljs.highlightElement(editor);
    }
    let runbtn=document.querySelector("#run-button");
    runbtn.addEventListener("click",function(){
        let code = jar.toString();
        console.log(code);
    });
</script> -->


        {%endblock%}

proggamera/courses/templates/fill_in_results.html
    {%if student_fill_result.first.result == 1 %}
        <i class="fa-solid fa-circle-check fa-2xl align-self-end"></i>
    {%else%}
     <i class="fa-solid fa-circle-xmark fa-2xl align-self-end"></i>
    {%endif%}